<?php

namespace Tautof\PlatformBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Tautof\UserBundle\Repository\UserRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository {

    public function getAdvertByModel($model_id) {

        $queryBuilder = $this->createQueryBuilder('a');
        $this->innerJoinMakeJoinModel($queryBuilder)
                ->andWhere('mo.id = :model')
                ->setParameter('model', $model_id);
        return $queryBuilder->getQuery()->getResult();
    }

    public function getAdvertByMake($make_id) {

        $queryBuilder = $this->createQueryBuilder('a');

        $this->innerJoinMakeJoinModel($queryBuilder)
                ->andWhere('ma.id = :make')
                ->setParameter('make', $make_id);



        return $queryBuilder->getQuery()->getResult();
    }

    public function innerJoinMakeJoinModel(QueryBuilder $qb) {

        $qb->innerJoin('a.model', 'mo');
        $qb->innerJoin('mo.make', 'ma');
        return $qb;
    }

    public function getAdvertByUser($user) {

        $queryBuilder = $this->createQueryBuilder('a')
                ->where('a.user = :user')
                ->setParameter('user', $user);

        return $queryBuilder->getQuery()->getResult();
    }

    public function editAdvert($adv, $modAdv) {

     
        

        $qd = $this->createQueryBuilder('a')
                ->update()
                ->set('a.title', ':title')
                ->setParameter('title', $modAdv->getTitle())
                ->set('a.model', ':model')
                ->setParameter('model', $modAdv->getModel())
                ->set('a.color',':color')
                ->setParameter('color', $modAdv->getColor())
                ->andWhere('a.id = :id')
                ->setParameter('id', $adv);
        return $qd->getQuery()->getResult();
    }

}
