# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Tautof\UserBundle\Entity\User: 
            algorithm: bcrypt
        
    role_hierarchy:
        ROLE_USER:        [ROLE_AUTEUR]
        ROLE_ADMIN:       [ROLE_USER, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
   
    providers:
        main: 
            entity:
                class: Tautof\UserBundle\Entity\User
                property: username

    firewalls:
       
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main_login:
            pattern: ^/login$
            anonymous: true
            provider: main
        
        main_registrer:
            pattern: ^/registrer$
            anonymous: true
            provider: main
        
        main: 
            pattern:         ^/
            anonymous:       false
            provider:        main
            http_basic: ~
            form_login:
                login_path:  login
                check_path:  login_check
                default_target_path: tautof_platform_homepage
            logout:
                path:        logout
                target:      /login
                
   
    
