oc_platform_homepage:
    path:     /
    defaults: 
        _controller: OCPlatformBundle:Default:index 
    
oc_platform_advert:
    path: /advert/{name}.{age}
    defaults:
        _controller: OCPlatformBundle:Advert:index 

oc_platform_welcome:
    path: /advert/welcome
    defaults: 
        _controller: OCPlatformBundle:Advert:redirectWelcome

oc_plateform_add:
    path: /advert/add
    defaults:
        _controller: OCPlatformBundle:Advert:add
oc_platform_view:
    path: advert/view
    defaults:
        _controller: OCPlatformBundle:Advert:view